# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15da59207eafb227adb9c58bf15ade42960e45082ca28d57e6b376ed321e85ac64479d04b24c159da51e63de0ef5f925ae6b2cf5e8a5daed46beb3f3c9d64f6d

test:
  secret_key_base: f424e8ae92ca259a9d68a37ca37dde603494bbc7a19d4b229c257a925208d9db505928740719bca1fc2aaa57b7fd5f8e0de4e4fbab23b656248a4f6e7eecec74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
